### ISSUE TITLE
Garbled output when loading files with CRLF line terminators

### ISSUE THREAD

**Issue by bradrn** [CrystalSplitter/ghcitui#25]
## Description

I just tried to test out GHCiTUI on my Haskell project [brassica](https://github.com/bradrn/brassica). However, several modules in that project appear to cause severe graphical glitches when loaded into GHCiTUI: rather than showing the code, they show numerous vertical lines scattered across the terminal, as well as distortion of other panels (especially `Modules`). Interestingly, each malfunctional module appears to result in exactly the same pattern of glitches when displayed.

### To Reproduce

- Clone https://github.com/bradrn/brassica and `git checkout 148b523`, to make sure you have the same code as me
- Run `ghcitui`
- Press `M`
- Try to load e.g. `Brassica.Paradigm` or `Brassica.SoundChange.Parse`. It should work without problems.
- Then try to load e.g. `Brassica.MDF` or `Brassica.Paradigm.Parse`. It should cause glitches.

### Expected behaviour

All modules show the source code when loaded.

### Screenshots

![image](https://github.com/CrystalSplitter/ghcitui/assets/17613703/aa61eb2b-5a67-47c0-b89a-7d5e6d7674c1)

### Environment

- OS: Linux: EndeavourOS (essentially Arch Linux)
- GHCiTUI Version: 0.1.0.0

**Comment by bradrn** [comment]
Update: someone suggested checking my line terminators. Indeed, it turns out that the files which don’t work are precisely those with CRLF line terminators!

**Comment by CrystalSplitter** [comment]
Thank for such an excellent report and troubleshooting! I'll take a look
this weekend.

**Comment by CrystalSplitter** [comment]
We need a new release to actually ship this fix out, but in theory this is fixed with the latest build.

**Comment by bradrn** [comment]
Thanks! It seems to be working now!
