### ISSUE TITLE
Tab completion support

### ISSUE THREAD

**Issue by bradrn** [CrystalSplitter/ghcitui#27]
## Description

I use tab completion quite a lot in GHCi. Alas, it doesn’t seem to work in GHCiTUI: pressing the Tab key shows `:complete <my input>` at the bottom of the Source pane, but it doesn’t actually show the completion in the GHCi pane. I’m not sure if this is due to a bug, or simply because it hasn’t been implemented yet — in which case, I’d like to request it if possible!

### To Reproduce

1. Open `ghcitui` and switch to the GHCi pane.
2. Type input and press the Tab key.

### Expected behaviour

The input is completed as in GHCi.

### Screenshots

Example of what happens after I press Tab:

![image](https://github.com/CrystalSplitter/ghcitui/assets/17613703/8b889d25-783f-437d-a733-d2fcbee9254a)

### Environment

- OS: Linux: EndeavourOS (essentially Arch Linux)
- GHCiTUI Version: 0.1.0.0

**Comment by CrystalSplitter** [comment]
Not implemented yet. There's actually a keybinding for it already, but it just doesn't parse the output from the tab completion correctly still.

**Comment by CrystalSplitter** [comment]
I'll add it to the next release, if you're willing to wait for the CRLF fix.

**Comment by bradrn** [comment]
Thanks for clarifying! Perhaps I’ll have a go at implementing this myself — the output doesn’t seem too difficult to parse.

**Comment by CrystalSplitter** [comment]
This is where the current code stub is, if you want to try! No worries if not.

https://github.com/CrystalSplitter/ghcitui/blob/main/lib/ghcitui-brick/Ghcitui/Brick/Events.hs#L117-L124

**Comment by CrystalSplitter** [comment]
Alright, `main` should now have this feature incorporated. Please reopen if it causes any problems! There were a lot of edge cases I encountered, and it's likely there are more.

**Comment by CrystalSplitter** [comment]
New version 0.2.0.0 on hackage supports this now (among a few other changes).
