### ISSUE TITLE
Thanks for making & maintaining this project!

### ISSUE THREAD

**Issue by cloudyluna** [CrystalSplitter/ghcitui#45]
I've been looking for something like this for a while now (got used to plain GHCi and wanted something like IPython to scratch that interactivity itch). Just wanna say thank you, that's all. :smiley:

**Comment by CrystalSplitter** [comment]
Oh, thank you! I'm glad you like it. c: The project was heavily inspired by Python's PuDB. Feel free to ask for any features or report any bugs! I'm very friendly.
